name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    - name: Build JAR
      run: ./gradlew clean build

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
          
    - name: Build the Docker image
      run: docker build --file Dockerfile --tag ${{ secrets.DOCKER_IMAGE_NAME }} .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_IMAGE_NAME }}

    - name: Connect to EC2 and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_IMAGE_NAME }}
          docker stop backend-server || true
          docker rm backend-server || true
          docker run -d --name backend-server -p 8080:8080 \
            -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
            -e JWT_ACCESS_EXPIRATION=${{ secrets.JWT_ACCESS_EXPIRATION }} \
            -e JWT_REFRESH_EXPIRATION=${{ secrets.JWT_REFRESH_EXPIRATION }} \
            -e RDS_ENDPOINT=${{ secrets.RDS_ENDPOINT }} \
            -e RDS_DB_NAME=${{ secrets.RDS_DB_NAME }} \
            -e RDS_DB_USERNAME=${{ secrets.RDS_DB_USERNAME }} \
            -e RDS_DB_PASSWORD=${{ secrets.RDS_DB_PASSWORD }} \
            -e AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }} \
            -e AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }} \
            -e AWS_REGION=${{ secrets.AWS_REGION }} \
            -e S3_BUCKETNAME=${{ secrets.S3_BUCKETNAME }} \
            -e SPRING_PROFILES_ACTIVE=prod \
            ${{ secrets.DOCKER_IMAGE_NAME }}
